language: node_js
node_js:
  - lts/*
# node 19 is broken
# see https://travis-ci.community/t/the-command-npm-config-set-spin-false-failed-and-exited-with-1-during/12909/8
#  - node
os: linux
dist: focal
arch: arm64
cache:
  directories:
    - .yarn/cache
    - src/__tests__/integration/fixtures/test-package-node-modules/.yarn/cache
    - src/__tests__/integration/fixtures/test-package-node-modules-aliases/.yarn/cache
    - src/__tests__/integration/fixtures/test-package-pnp/.yarn/cache
    - src/__tests__/integration/fixtures/test-package-pnpm/.yarn/cache
