language: node_js
node_js:
  - lts/*
  - node
os: linux
dist: focal
arch: arm64
cache:
  directories:
    - .yarn/cache
    - src/__tests__/integration/fixtures/test-package-node-modules/.yarn/cache
    - src/__tests__/integration/fixtures/test-package-node-modules-aliases/.yarn/cache
    - src/__tests__/integration/fixtures/test-package-pnp/.yarn/cache
